import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <nav className="flex border-b border-gray-200 p-4" style={{height:"10px",  alignItems:"center"}}>
          <h1 className="font-bold" style={{fontSize: "40px", margin:"0px"}}>Auto Choice</h1>
        </nav>
        {children}</body>
    </html>
  );
}
